# Generated by Django 3.0.6 on 2022-06-19 12:47

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='pathScore',
            fields=[
                ('s_id', models.AutoField(primary_key=True, serialize=False)),
                ('path_id', models.CharField(max_length=50)),
                ('score', models.FloatField(blank=True, null=True)),
                ('predictionTask', models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='Username',
            fields=[
                ('username', models.CharField(max_length=50, primary_key=True, serialize=False)),
                ('sex', models.CharField(max_length=10)),
                ('age', models.IntegerField()),
                ('education', models.CharField(max_length=20)),
                ('research', models.CharField(max_length=100)),
            ],
        ),
    ]
